services:
  postgres:
    image: postgres:16
    container_name: mt-facturation-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "Yassine1@;"
      POSTGRES_DB: mt_facturation
    ports:
      - "5432:5432"
    volumes:
      - mt_facturation_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mt_facturation"]
      interval: 10s
      timeout: 5s
      retries: 10

  postgres_test:
    image: postgres:16
    container_name: mt-facturation-postgres-test
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "Yassine1@;"
      POSTGRES_DB: mt_facturation_test
    ports:
      - "5433:5432"
    tmpfs:
      - /var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mt_facturation_test"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  mt_facturation_pg_data:
